-- Rename PHYSICAL_INSPECTION to AI_ANALYSIS in WorkflowStep enum
ALTER TYPE "WorkflowStep" RENAME VALUE 'PHYSICAL_INSPECTION' TO 'AI_ANALYSIS';

-- Rename FINDINGS_RECORDED to AI_ANALYZED in InspectionStatus enum
ALTER TYPE "InspectionStatus" RENAME VALUE 'FINDINGS_RECORDED' TO 'AI_ANALYZED';

-- Add new CaptureType enum values
ALTER TYPE "CaptureType" ADD VALUE 'FRONT_34_PASSENGER';
ALTER TYPE "CaptureType" ADD VALUE 'REAR_34_PASSENGER';
ALTER TYPE "CaptureType" ADD VALUE 'ROOF';
ALTER TYPE "CaptureType" ADD VALUE 'UNDERCARRIAGE';
